name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * *"   # chạy mỗi ngày 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your profile repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone jstrieb/github-stats
        run: |
          git clone --depth=1 https://github.com/jstrieb/github-stats stats-src

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r stats-src/requirements.txt

      - name: Generate images with jstrieb/github-stats
        working-directory: stats-src
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   # PAT (khuyến nghị)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # có sẵn
          EXCLUDED: ${{ secrets.EXCLUDED }}           # tùy chọn: "repo1,repo2"
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }} # tùy chọn: "HTML,TeX"
        run: |
          python --version
          python generate_images.py
          mkdir -p ../generated
          cp -f generated/*.svg ../generated/

      - name: Commit SVGs to your repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/*.svg || true
          git commit -m "chore: update stats svg" || echo "No changes"
          git push
